// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7qC-7F4CmPxkEXDzoKR6i1eAKvteTVEg',
    appId: '1:162546141636:web:2969fd4daaa1936e54fc91',
    messagingSenderId: '162546141636',
    projectId: 'my-notesapp-new',
    authDomain: 'my-notesapp-new.firebaseapp.com',
    storageBucket: 'my-notesapp-new.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQkGDi8SKAoNbfKNK0lYebo8lB1wNitg',
    appId: '1:162546141636:android:1ac7ef68d136f7e054fc91',
    messagingSenderId: '162546141636',
    projectId: 'my-notesapp-new',
    storageBucket: 'my-notesapp-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm_T_q08twtXdUzPRS7UgRBP_9lSBDko0',
    appId: '1:162546141636:ios:978c09208a5f363654fc91',
    messagingSenderId: '162546141636',
    projectId: 'my-notesapp-new',
    storageBucket: 'my-notesapp-new.appspot.com',
    iosBundleId: 'com.example.noteAppUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm_T_q08twtXdUzPRS7UgRBP_9lSBDko0',
    appId: '1:162546141636:ios:16230a765b55b8ef54fc91',
    messagingSenderId: '162546141636',
    projectId: 'my-notesapp-new',
    storageBucket: 'my-notesapp-new.appspot.com',
    iosBundleId: 'com.example.noteAppUsingFirebase.RunnerTests',
  );
}
