// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0p3Mgvc52FnsKEH5-JbjM7f92jUfBwno',
    appId: '1:767905707561:web:e6c77a4a7b77d31c5ece38',
    messagingSenderId: '767905707561',
    projectId: 'note-app-186b2',
    authDomain: 'note-app-186b2.firebaseapp.com',
    storageBucket: 'note-app-186b2.appspot.com',
    measurementId: 'G-EBWPQX1ZG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmn-xL_xStWYgiRhOtmmo5gOBaj5CxeP8',
    appId: '1:767905707561:android:0cc3d0613eac6afa5ece38',
    messagingSenderId: '767905707561',
    projectId: 'note-app-186b2',
    storageBucket: 'note-app-186b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LecjiQUb9ILrCS_F99llsNIkrHxPyAs',
    appId: '1:767905707561:ios:2b3072eedb6e91485ece38',
    messagingSenderId: '767905707561',
    projectId: 'note-app-186b2',
    storageBucket: 'note-app-186b2.appspot.com',
    iosBundleId: 'com.example.noteAppUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5LecjiQUb9ILrCS_F99llsNIkrHxPyAs',
    appId: '1:767905707561:ios:0f3da9a9e4b36ef95ece38',
    messagingSenderId: '767905707561',
    projectId: 'note-app-186b2',
    storageBucket: 'note-app-186b2.appspot.com',
    iosBundleId: 'com.example.noteAppUsingFirebase.RunnerTests',
  );
}
